# Generated by Django 4.1.7 on 2023-03-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbv", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(null=True, upload_to="posts_cbv/"),
        ),
    ]
